import json
import os
import sys
import random
import argparse

# Add project root to path so we can import src
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '../..')))

from src.core.database import GenericDatabase
from src.domain.models import Question, Event, EventOutcomeImpact

def export_for_annotation(db_path="worldreasoner.db", output_file="scripts/annotation_ui/annotation_data.js", seed=42, sample_size=50):
    db = GenericDatabase(db_path)
    
    questions = db.get_many(Question)
    if not questions:
        print(f"No questions found in database: {db_path}")
        return

    # ONLY keep questions that actually have at least one event with an impact analysis
    # This prevents exporting boring/empty questions to the annotator.
    import sqlite3
    temp_conn = sqlite3.connect(db_path)
    temp_cursor = temp_conn.cursor()
    temp_cursor.execute('''
        SELECT DISTINCT e.extracted_for_question_id 
        FROM events e
        JOIN event_outcome_impacts i ON e.id = i.event_id
        WHERE e.extracted_for_question_id IS NOT NULL
    ''')
    valid_q_ids = set([r[0] for r in temp_cursor.fetchall()])
    
    questions = [q for q in questions if q.id in valid_q_ids]
    
    # 【引入 Seed 机制】打乱顺序以保证每次相同 seed 导出的样本是一致且随机的
    random.seed(seed)
    random.shuffle(questions)

    export_data = []
    question_count = 0
    event_count = 0

    for q in questions:
        # Update field name to 'extracted_for_question_id' based on the DB schema
        events = db.get_many(Event, filters={"extracted_for_question_id": q.id})
        
        # Only export questions that actually have events generated by the Hindsight Agent
        if not events:
            continue
            
        # Sort events chronologically if date is available
        try:
            events = sorted(events, key=lambda e: getattr(e, 'occurred_date', getattr(e, 'date', '')))
        except:
            pass

        q_data = {
            "id": q.id,
            "title": q.question_text,
            "background": getattr(q, 'context', 'No background available.') or 'No background available.',
            "resolution_criteria": getattr(q, 'resolution_criteria', 'No criteria available.') or 'No criteria available.',
            "outcome": getattr(q, 'ground_truth', 'Unknown'),
            "explanation": getattr(q, 'causal_explanation') or getattr(q, 'resolution_reasoning', 'No causal explanation available.') or 'No causal explanation available.',
            "events": []
        }

        valid_events = []
        for e in events:
            # Skip events that are already auto-approved outcome events
            if getattr(e, 'review_note', '') == "Auto-approved (outcome event)":
                continue

            current_status = getattr(e, 'review_status', 'pending')
            if hasattr(current_status, "value"):
                current_status = current_status.value
            
            # 【核心过滤】跳过被机器 auto-review 判定为 rejected 的无用事件
            if current_status == "rejected":
                continue

            # Format the date nicely if it's a datetime object
            date_val = getattr(e, 'occurred_date', getattr(e, 'date', 'Unknown Date'))
            if hasattr(date_val, 'strftime'):
                date_val = date_val.strftime("%Y-%m-%d %H:%M")
                
            # Try to get impact reasoning from DB mapping table if available
            impact_text = 'No impact assessment provided.'
            try:
                # Need to use plain tuple fetch since EventOutcomeImpact model might not exactly match column names or the object isn't fully loading
                temp_cursor.execute("SELECT impact_direction, reasoning, impact_magnitude, confidence, outcome_event_id FROM event_outcome_impacts WHERE event_id = ?", (e.id,))
                impact_row = temp_cursor.fetchone()
                if impact_row:
                    dir_val = str(impact_row[0]).replace('ImpactDirection.', '').capitalize()
                    mag_val = impact_row[2]
                    conf_val = impact_row[3]
                    outcome_event_id = impact_row[4]
                    
                    outcome_title = "Unknown Outcome"
                    if outcome_event_id:
                        temp_cursor.execute("SELECT title FROM events WHERE id = ?", (outcome_event_id,))
                        outcome_row = temp_cursor.fetchone()
                        if outcome_row and outcome_row[0]:
                            outcome_title = outcome_row[0]
                    
                    mag_str = f" ({int(mag_val * 100)}%)" if mag_val is not None else ""
                    conf_str = f" | **Confidence:** {int(conf_val * 100)}%" if conf_val is not None else ""
                    
                    impact_text = f"**Affects:** {outcome_title}  \n**Impact:** {dir_val}{mag_str}{conf_str}\n\n**Reasoning:**\n{impact_row[1]}"
            except Exception as ex:
                pass
                
            # Try to get source snippet AND URL
            source_text = 'No direct snippet available.'
            article_url = None
            try:
                # If there are article IDs, fetch the first one
                article_id_to_fetch = None
                
                # Try source_article_id directly
                if hasattr(e, 'source_article_id') and e.source_article_id:
                    article_id_to_fetch = e.source_article_id
                # Or try article_ids JSON array
                elif hasattr(e, 'article_ids') and e.article_ids:
                    import json as inner_json
                    a_ids = inner_json.loads(e.article_ids)
                    if a_ids and len(a_ids) > 0:
                        article_id_to_fetch = a_ids[0]
                        
                if article_id_to_fetch:
                    # In worldreasoner.db the schema has 'url' and 'content' 
                    temp_cursor.execute("SELECT content, url FROM articles WHERE id = ?", (article_id_to_fetch,))
                    art_row = temp_cursor.fetchone()
                    if art_row:
                        # snippet using the first 200 chars of content
                        full_content = art_row[0] if art_row[0] else ""
                        source_text = (full_content[:250] + '...') if len(full_content) > 250 else (full_content or "Article content missing.")
                        article_url = art_row[1]
            except Exception as ex:
                pass
                
            # Use safe defaults for marked.js parsing
            exp_text = getattr(q, 'causal_explanation') or getattr(q, 'resolution_reasoning') or 'No causal explanation available.'
            
            # Make sure impact text isn't empty for markdown parsing
            if not impact_text: impact_text = 'No impact assessment provided.'

            valid_events.append({
                "id": e.id,
                "date": date_val,
                "title": getattr(e, 'title', 'Untitled Event'),
                "description": getattr(e, 'description', getattr(e, 'summary', '')),
                "impact": impact_text,
                "source_snippet": source_text,
                "source_url": article_url,
                "current_status": current_status,
                "reasoning_status": None
            })

        # 【核心过滤】如果一个问题的有效事件依然超过12个，进行均匀时间线采样
        if len(valid_events) > 12:
            step = len(valid_events) / 12.0
            valid_events = [valid_events[int(i * step)] for i in range(12)]

        q_data["events"] = valid_events
        
        # Only add question if there are actual events to review
        if q_data["events"]:
            export_data.append(q_data)
            event_count += len(valid_events)
            question_count += 1
            
            # 达到样本数量即停止
            if question_count >= sample_size:
                break

    # Write as a JS file so the HTML can just include it via <script>
    with open(output_file, "w", encoding="utf-8") as f:
        f.write(f"const annotationData = {json.dumps(export_data, indent=2, ensure_ascii=False)};")
        
    print(f"✅ Exported {len(export_data)} questions and {event_count} events to {output_file} (Seed: {seed})")
    print("💡 You can now open 'scripts/annotation_ui/index.html' in your browser.")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Export data for UI annotation.")
    parser.add_argument("--db", default="worldreasoner.db", help="Path to SQLite DB")
    parser.add_argument("--out", default="scripts/annotation_ui/annotation_data.js", help="Output JS file")
    parser.add_argument("--seed", type=int, default=42, help="Random seed for sampling")
    parser.add_argument("--sample", type=int, default=50, help="Number of questions to sample")
    
    args = parser.parse_args()
    
    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    export_for_annotation(db_path=args.db, output_file=args.out, seed=args.seed, sample_size=args.sample)